name: Main CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - master
        
env:
  BUILD_CONFIGURATION: "Release"
  DOCKER_IMAGE_NAME_API: "expensetrackerapi"
  PATH_TO_CSPROJ_API: "./src/CabaVS.ExpenseTracker.API/CabaVS.ExpenseTracker.API.csproj"
  PATH_TO_GLOBAL_JSON: "./global.json"
  
jobs:
  build:
    name: Build API project
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: ${{ env.PATH_TO_GLOBAL_JSON }}
          
      - name: Restore
        run: dotnet restore ${{ env.PATH_TO_API }}
        
      - name: Build
        run: dotnet build ${{ env.PATH_TO_API }} --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore
        
  push-image:
    name: Push image to ACR
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v4
          
      - name: Set image tags
        id: vars
        run: |
          echo "sha_tag=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
          
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.DOCKER_IMAGE_NAME_API }}:latest \
            -t ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.DOCKER_IMAGE_NAME_API }}:${{ steps.vars.outputs.sha_tag }} .
          
      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Docker Login to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Push image to ACR
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.DOCKER_IMAGE_NAME_API }}:latest
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.DOCKER_IMAGE_NAME_API }}:${{ steps.vars.outputs.sha_tag }}